apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-kskf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-kskf
    app.kubernetes.io/part-of: test-app-hrpw
  name: test-component-kskf
  namespace: build-e2e-utia-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-kskf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-kskf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:14c8aa0e73102f2c56f092c1522558bed56541a4a4a450c99a268e073803d86e
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
